

var ele =  {ref:1,type:'div',style:{backgroundColor:'brown'},
           children:[
                  {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'20',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                   },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
                     {ref:'1',type:'div',style:{backgroundColor:'red',margin:'20dp'},
                     children:[{ref:'1',type:'div',style:{backgroundColor:'yellow',margin:'20dp'},
                           children:[{ref:'1',type:'div',style:{backgroundColor:'blue',height:'200px',margin:'20dp'},
                                     
                                     }],
                               }],
                     },
               
              ]
            }
callNative(1,[{module:'dom',method:'createBody',args:[ele]}])



setTimeout(function(){
         //  callNative(1,[{module:'dom',method:'createBody',args:[ele]}])
           },2000);


function createInstance(instanceId,data){
    
}
